apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification # has to match .metadata.labels.app && template.metadata.labels.app of deployment || stafulset
  ports:
    - port: 8040
      targetPort: 8040 # has to match containerPort of deployment || stafulset
  type: NodePort #IP address
