version: "3.8"
services:
  mysql:
    container_name: mysql-db
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge
volumes:
  data:
