version: "3.8"
services:
  mysql:
    container_name: mysql-db
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
networks:
  mysql:
    driver: bridge
volumes:
  data:
