#Server
server:
  port: 8020
  error:
    include-message: always
#Spring
spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://mysql-db:3306/product
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  zipkin:
    baseUrl: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true