apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: ntloc/notification:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8040
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      restartPolicy: Always