apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer # has to match .metadata.labels.app && template.metadata.labels.app of deployment || stafulset
  ports:
    - port: 8010
      targetPort: 8010 # has to match containerPort of deployment || stafulset
      nodePort: 31610
  type: LoadBalancer #IP address
