server:
  port: 8030
  error:
    include-message: always
spring:
  application:
    name: orders
  zipkin:
    baseUrl: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3307/orders
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true