server:
  port: 8040
  error:
    include-message: always
spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost:3307/notification
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  zipkin:
    baseUrl: http://localhost:9411
  rabbitmq:
      addresses: localhost:5672
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
#RabbitMQ
rabbitmq:
  exchange:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-key:
    internal-notification: internal.notification.routing-key
