#Server
server:
  port: 8040
  error:
    include-message: always
#Spring
spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://aws-rds.cgxgnpipxxxq.ap-southeast-1.rds.amazonaws.com:3306/notification
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  zipkin:
    baseUrl: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
#Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
#RabbitMQ
rabbitmq:
  exchange:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-key:
    internal-notification: internal.notification.routing-key
